#pragma once
#include "Rendering/Settings.h"
#include "Core.h"
#include "MemoryTracker.h"
#include <memory>
#include <string>
#include <iostream>
#include <vector>
#include <tuple>
#include "Types.h"
#include "glm.hpp"
