#version 450

#define mipMaps 9

layout(binding = 0, rgba32f) uniform readonly image2D storageImage[mipMaps];

layout(binding = 1, rgba32f) uniform writeonly image2D final;

layout (local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

void main()
{
    ivec2 finalSize = imageSize(final);
    ivec2 coords = ivec2(gl_GlobalInvocationID.xy);

    
    if (coords.x >= finalSize.x || coords.y >= finalSize.y)
        return;

    vec2 uv = (vec2(coords) + 0.5) / vec2(finalSize);

   
    vec4 best = vec4(-1.0, -1.0, -1.0, -1.0);

    
    for (int i = 0; i < mipMaps; ++i)
    {
        ivec2 mipSize  = imageSize(storageImage[i]);
        ivec2 mipCoord = ivec2(uv * vec2(mipSize));
        vec4 texel     = imageLoad(storageImage[i], mipCoord);

       
        if (texel.x != -1.0 && texel.z > best.z)
        {
            best = texel;
        }
    }

    imageStore(final, coords, best);
}
